import express from "express";
const router = express.Router();
import userRoutes from "./user.routes";
import authRoutes from "./auth.routes";
import adminRoutes from "./admin.routes";
import orderRoutes from "./order.routes";
import { authorizeRoles, isAuthenticated } from "../middleware/auth";
import { addAnswer, getAllCourses, getCourseById } from "../controllers/course.controller";
router.get("/courses", getAllCourses);
router.get("/course/:id", getCourseById);
router.use("/auth", authRoutes);
router.use("/user", isAuthenticated, authorizeRoles("user"), userRoutes);
router.use("/order", isAuthenticated, authorizeRoles("user"), orderRoutes);
router.use("/admin", isAuthenticated, authorizeRoles("admin"), adminRoutes);
export default router;
